CREATE TABLE vulnerabilidades (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2 (100) NOT NULL,
    descripcion VARCHAR2 (4000) NOT NULL,
    severidad VARCHAR2 (20) NOT NULL,
    estado VARCHAR2 (20) DEFAULT 'ABIERTA',
    fecha_creacion DATE DEFAULT SYSDATE
);

INSERT INTO vulnerabilidades (
    titulo,
    descripcion,
    severidad
) VALUES (
    'Inyección de SQL en Login',
    'El parámetro de entrada de usuario no está sanitizado.',
    'CRITICA'
);

COMMIT;
